### ISSUE TITLE
Attempt to invoke virtual method 'com.BoardiesITSolutions.AndroidMySQLConnector.Connection com.BoardiesITSolutions.AndroidMySQLConnector.MySQLIO.getConnection()' on a null object reference

### ISSUE THREAD

**Issue by MatsG23** [BoardiesITSolutions/Android-MySQL-Connector#15]
Hello,

I'm experiencing this error: 
`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: mats.app.mysqltest, PID: 16119
    java.lang.RuntimeException: Unable to start activity ComponentInfo{mats.app.mysqltest/mats.app.mysqltest.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.BoardiesITSolutions.AndroidMySQLConnector.Connection com.BoardiesITSolutions.AndroidMySQLConnector.MySQLIO.getConnection()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3122)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6923)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.BoardiesITSolutions.AndroidMySQLConnector.Connection com.BoardiesITSolutions.AndroidMySQLConnector.MySQLIO.getConnection()' on a null object reference
        at com.BoardiesITSolutions.AndroidMySQLConnector.Connection.createStatement(Connection.java:807)
        at mats.app.mysqltest.MainActivity.onCreate(MainActivity.java:96)
        at android.app.Activity.performCreate(Activity.java:7148)
        at android.app.Activity.performCreate(Activity.java:7139)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1293)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3261) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1977) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6923) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:870) `

This is my code:
`IConnectionInterface ici = new IConnectionInterface() {
            @Override
            public void actionCompleted() {
                System.out.println("Connected");
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleMySQLException(MySQLException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleIOException(IOException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleMySQLConnException(MySQLConnException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleException(Exception ex) {
                ex.printStackTrace();
            }
        };
        IResultInterface iri = new IResultInterface() {
            @Override
            public void executionComplete(ResultSet resultSet) {
                System.out.println(resultSet.getFields());
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleMySQLException(MySQLException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleIOException(IOException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleMySQLConnException(MySQLConnException ex) {
                ex.printStackTrace();
            }

            @Override
            public void handleException(Exception ex) {
                ex.printStackTrace();
            }
        };

        Connection connection = new Connection(CREDENTIALS);
        Statement statement = connection.createStatement();
        statement.executeQuery("SELECT * FROM Benutzernamen", iri);`

The error appears at the line 
`Statement statement = connection.createStatement();`
I'm importing right statement class

Best Regards
MatsG23

**Comment by boardy** [comment]
Hey, 

It doesn't appear you are actually making using of IConnectionResult. This needs to be used as part of the actual connection object as the second parameter, not sure how you haven't got a second parameter, are you sure you are not importing from java.sql instead of the AndroidMySQLConnector library. 

At the moment you are creating a connection and then straight after trying to create a statement. The library work asyonchously, so as soon as you create the connection object, it starts establishing the connection to the server, but when your statement is then used, the connection object hasn't yet been initialised fully so you get the null pointer exception. 

You should have something similar to the below
```
Connection conn = new Connection("host", "username", "password", port, new IConnectionInterface(){
 @Override
                public void actionCompleted()
                {
                    Log.d("MainActivity", "Database Connected Successfully");
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run()
                        {
                            Statement statement = conn.createStatement()
                        }
                    });
                }
}
```

There should be a demo application within the library project that shows how the library should be used. 

Hope this helps but let me know if you have any other issues

Thanks

Chris

**Comment by boardy** [comment]
No further response so closing - if you are having this issue please re-open this instead of creating a new issue.
