### ISSUE TITLE
MySQLConnException

### ISSUE THREAD

**Issue by Asuki** [BoardiesITSolutions/Android-MySQL-Connector#9]
Hi!

I tried to connect to database with the following code. And I get a n error 
(03-21 04:52:56.928 3261-3614/automentomano.hu D/DatabaseHelper: handleMySQLConnException: com.BoardiesITSolutions.AndroidMySQLConnector.Exceptions.MySQLConnException: **Got packets out of order**)

mysqlConnection = new Connection("185.51.191.28", "<Username>", "<Password>", 3306, "<Database>", new IConnectionInterface()
        {
            @Override
            public void actionCompleted()
            {
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException e)
            {
                //Handle the error
            }

            @Override
            public void handleMySQLException(MySQLException e)
            {
                //Handle the error
            }

            @Override
            public void handleIOException(IOException e)
            {
                //Handle the error
            }

            @Override
            public void handleMySQLConnException(MySQLConnException e)
            {
                //Handle the error
                Log.d(TAG, "handleMySQLConnException: " + e.toString());
            }

            @Override
            public void handleException(Exception e)
            {
                //Handle the error
            }
        });

How can I connect to database?

Thanks,
Seng

**Comment by boardy** [comment]
Hi Seng, 

I notice the username and password is a blank string, I assume that's just so you are not posting your login details, but your database is a blank string, are you actually providing a proper database name instead of a blank string as that may cause some weird results, if you don't want to connect with a default database you can leave this parameter out. 

Otherwise can you let me know which version MySQL you are trying to connect to.

Thanks

Chris

**Comment by boardy** [comment]
Hi Seng, 

I've just done a test and doesn't look like setting the database to a blank string would be the cause, so going to need the MySQL version to look into further. 

If you could let me know as well how the database is hosted, e.g. is it a server you've installed and ran the MySQL installer on Windows/Linux, or is it a managed database service like Amazon RDS?

Thanks

Chris

**Comment by Asuki** [comment]
Hi!

I just did not posted the login information (login and password) and I also didn't posted the database too. So I didn't left the database blank.

**Comment by Asuki** [comment]
> Otherwise can you let me know which version MySQL you are trying to connect to.

The MySQL version is 5.6.43

**Comment by Asuki** [comment]
> If you could let me know as well how the database is hosted, e.g. is it a server you've installed and ran the MySQL installer on Windows/Linux, or is it a managed database service like Amazon RDS?

There is a webpage: http://somogyvari.automentorendelo.hu 
with login and service. I trying to connect to its database. I have the database name, password and username of corse.

Thanks,
Seng

**Comment by boardy** [comment]
Hi Seng, 

I've installed that MySQL server version on my own server and it appears to work OK so its something specific that database service by the looks. I tried to create an account but it doesn't look possible. 

Would you be able to create a temporary account - don't need to give me any permissions just enough to connect and I'll perform some LAN traces and see what MySQL packets I'm getting and how they are being processed by the library. 

Thanks

Chris

**Comment by Asuki** [comment]
Hi!

I asked a test user with onlin select permission. I sent it by e-mail to support@boardiesitsolutions.com e-mail address.

**Comment by boardy** [comment]
Hi, 

Thanks I got the login details, sorry meant to give you that email in my last comment save you looking for it.

I'll give it a try and let you know when I've identifed the issue and hopefully be able to provide a fix for it ASAP.

Thanks

Chris

**Comment by Asuki** [comment]
Thanks for your quick answer. I'm wainting for it.

Thanks,
Seng

**Comment by boardy** [comment]
Hi Seng, 

Did you get my email the other day, I tried the login details you sent me but I got an access denied error back?

Thanks

**Comment by Asuki** [comment]
Hi!

I didn't get an amail. Did you send it to phraseng@gmail.com? Can you give me your ip address? 

Tanks

**Comment by boardy** [comment]
Hi, 

I just replied to your email, it looks like it was sent from a different address. My IP Address is 86.186.132.65. Its a home broadband so it might change if I reboot the router which I have to do every now and again unfortunately. 

Thanks

**Comment by Asuki** [comment]
Can you use with this ip address: 185.51.191.28 instead of host name?

**Comment by boardy** [comment]
Fraid not, still get an access denied error.

**Comment by Asuki** [comment]
I asked a permission to your ip.

**Comment by boardy** [comment]
Hi Seng, 

I've connected now although unfortunately don't seem to be exhibiting the issue you are seeing with the connection out of order. Are you using the latest tag release (0.26). 

I have found another problem though where when running SHOW TABLES although the query completes it doesn't fully process the response so it doesn't list the tables in the resultset so I'll be releasing another version to fix this.

**Comment by boardy** [comment]
Hi Seng, 

I've just realsed version 0.27 which fixes the issues with query responses from above. If you can give this version a try and let me know how you get on. 

I'm not able to replicate the packet out of order problem as the connection appears to be OK so if you still having that issue on this new release can you let me know which Android version you are using?

Thanks

Chris

**Comment by Asuki** [comment]
Hi!

I tried it with the 0.27 version. I'm using Lollypop (5.1), but I tried it with Oreo (8.0). I got the same problem.

I tested it with a new program (I used a simply activity to create projcet).
I created a database helper and I called it in MainActivity.java.

-----------------------------------------------------------------------------------------------------------
DatabaseHelper
-----------------------------------------------------------------------------------------------------------
```
import android.util.Log;

import com.BoardiesITSolutions.AndroidMySQLConnector.Connection;
import com.BoardiesITSolutions.AndroidMySQLConnector.Exceptions.InvalidSQLPacketException;
import com.BoardiesITSolutions.AndroidMySQLConnector.Exceptions.MySQLConnException;
import com.BoardiesITSolutions.AndroidMySQLConnector.Exceptions.MySQLException;
import com.BoardiesITSolutions.AndroidMySQLConnector.IConnectionInterface;
import com.BoardiesITSolutions.AndroidMySQLConnector.IResultInterface;
import com.BoardiesITSolutions.AndroidMySQLConnector.ResultSet;
import com.BoardiesITSolutions.AndroidMySQLConnector.Statement;

import java.io.IOException;

public class DatabaseHelper {
    Connection mysqlConnection;
    final String TAG = "DatabaseHelper";

    public DatabaseHelper(){
        Log.d(TAG, "DatabaseHelper: constructor ready");
        mysqlConnection = new Connection(/*Here I used the connection information what I sent to you.*/, new IConnectionInterface()
        {
            @Override
            public void actionCompleted()
            {
                Log.d(TAG, "actionCompleted: connected xxxxx");
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException e)
            {
                //Handle the error
                Log.d(TAG, "handleInvalidSQLPacketException: xxxxx");
            }

            @Override
            public void handleMySQLException(MySQLException e)
            {
                //Handle the error
                Log.d(TAG, "handleMySQLException: xxxxx " + e.toString() + "------------------------------------------------------");
                Log.d(TAG, "handleMySQLException: " + e.toString());
                Log.d(TAG, "handleMySQLException: ------------------------------------------------------------------");
            }

            @Override
            public void handleIOException(IOException e)
            {
                //Handle the error
                Log.d(TAG, "handleIOException: xxxxx");
            }

            @Override
            public void handleMySQLConnException(MySQLConnException e)
            {
                //Handle the error
                Log.d(TAG, "handleMySQLConnException: xxxxx");
                Log.d(TAG, "handleMySQLConnException: " + e.toString());
                Log.d(TAG, "handleMySQLConnException: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++");
            }

            @Override
            public void handleException(Exception e)
            {
                //Handle the error
                Log.d(TAG, "handleException: xxxxx");
            }
        });


        Statement statement = mysqlConnection.createStatement();
        Log.d(TAG, "DatabaseHelper: Connection started");
        statement.executeQuery("SELECT * FROM pricer", new IResultInterface() {
            @Override
            public void executionComplete(ResultSet resultSet) {
                Log.d(TAG, "executionComplete: before getNumRows");
                Log.d(TAG, "executionComplete: " + resultSet.getNumRows());
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException ex) {

            }

            @Override
            public void handleMySQLException(MySQLException ex) {

            }

            @Override
            public void handleIOException(IOException ex) {

            }

            @Override
            public void handleMySQLConnException(MySQLConnException ex) {

            }

            @Override
            public void handleException(Exception ex) {

            }
        });

    }
}
```
=================================================================

----------------------------------------------------------------------------------------------------------------
Logcat
----------------------------------------------------------------------------------------------------------------
2019-04-01 07:22:29.457 3380-3380/? I/zygote: Not late-enabling -Xcheck:jni (already on)
2019-04-01 07:22:29.478 3380-3380/? W/zygote: Unexpected CPU variant for X86 using defaults: x86
2019-04-01 07:22:31.063 3380-3380/hu.utomentomano.mysqltestv3 I/InstantRun: starting instant run server: is main process
2019-04-01 07:22:31.918 3380-3380/hu.utomentomano.mysqltestv3 D/DatabaseHelper: DatabaseHelper: constructor ready
2019-04-01 07:22:31.941 3380-3380/hu.utomentomano.mysqltestv3 D/DatabaseHelper: DatabaseHelper: Connection started
2019-04-01 07:22:31.953 3380-3380/hu.utomentomano.mysqltestv3 D/Connection: Packet Sequence Number Returned: 0
2019-04-01 07:22:32.038 3380-3430/hu.utomentomano.mysqltestv3 D/OpenGLRenderer: HWUI GL Pipeline
2019-04-01 07:22:32.077 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Resetting Socket: Don't Expect Response: false
2019-04-01 07:22:32.077 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: socket data has reset. Getting socket data
2019-04-01 07:22:32.077 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Reading Socket Data
2019-04-01 07:22:32.077 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Created baos
2019-04-01 07:22:32.078 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Read from socket. Bytes Read: 82
2019-04-01 07:22:32.078 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: BAOS written: Bytes Written: 82
2019-04-01 07:22:32.078 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Receiving less data than buffer filled. Checking for EOF
2019-04-01 07:22:32.078 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: EOF detected, breaking loop and processing response
2019-04-01 07:22:32.078 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Loop completed
2019-04-01 07:22:32.078 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Full data written to: now size: 82
2019-04-01 07:22:32.086 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLConnection: Sending Auth Response
2019-04-01 07:22:32.089 3380-3429/hu.utomentomano.mysqltestv3 D/AuthResponse: Going to write server language: 0x21
2019-04-01 07:22:32.092 3380-3429/hu.utomentomano.mysqltestv3 D/Connection: Packet Sequence Number Returned: 0
2019-04-01 07:22:32.095 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Socketdata written and about to reset
2019-04-01 07:22:32.095 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Resetting Socket: Don't Expect Response: false
2019-04-01 07:22:32.095 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: socket data has reset. Getting socket data
2019-04-01 07:22:32.095 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Reading Socket Data
2019-04-01 07:22:32.095 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Created baos
2019-04-01 07:22:32.105 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Read from socket. Bytes Read: 37
2019-04-01 07:22:32.105 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: BAOS written: Bytes Written: 37
2019-04-01 07:22:32.105 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Receiving less data than buffer filled. Checking for EOF
2019-04-01 07:22:32.106 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Loop completed
2019-04-01 07:22:32.106 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Full data written to: now size: 37
2019-04-01 07:22:32.106 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Socket data reset method has been called. Going to call socket data sent interface
2019-04-01 07:22:32.106 3380-3429/hu.utomentomano.mysqltestv3 D/Connection: Socket Data Sent
2019-04-01 07:22:32.108 3380-3429/hu.utomentomano.mysqltestv3 D/DatabaseHelper: handleMySQLConnException: xxxxx
2019-04-01 07:22:32.108 3380-3429/hu.utomentomano.mysqltestv3 D/DatabaseHelper: handleMySQLConnException: com.BoardiesITSolutions.AndroidMySQLConnector.Exceptions.MySQLConnException: Got packets out of order
2019-04-01 07:22:32.108 3380-3429/hu.utomentomano.mysqltestv3 D/DatabaseHelper: handleMySQLConnException: +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
2019-04-01 07:22:32.108 3380-3429/hu.utomentomano.mysqltestv3 D/MySQLIO: Calling socket data sent interface
2019-04-01 07:22:32.122 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: Resetting Socket: Don't Expect Response: false
2019-04-01 07:22:32.122 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: socket data has reset. Getting socket data
2019-04-01 07:22:32.122 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: Reading Socket Data
2019-04-01 07:22:32.122 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: Created baos
2019-04-01 07:22:32.122 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: Loop completed
2019-04-01 07:22:32.122 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: No data in response
2019-04-01 07:22:32.123 3380-3432/hu.utomentomano.mysqltestv3 D/MySQLIO: Full data written to: now size: 0
2019-04-01 07:22:32.123 3380-3432/hu.utomentomano.mysqltestv3 D/Statement: Interface for SocketDataSent called
2019-04-01 07:22:32.123 3380-3432/hu.utomentomano.mysqltestv3 W/System.err: java.io.IOException: Unexpected SQL Packet Size. Got Size: 0
2019-04-01 07:22:32.123 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at com.BoardiesITSolutions.AndroidMySQLConnector.Helpers.getMySQLPacketType(Helpers.java:20)
2019-04-01 07:22:32.123 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at com.BoardiesITSolutions.AndroidMySQLConnector.Statement$2.socketDataSent(Statement.java:201)
2019-04-01 07:22:32.124 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at com.BoardiesITSolutions.AndroidMySQLConnector.SocketSender.doInBackground(SocketSender.java:53)
2019-04-01 07:22:32.124 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at com.BoardiesITSolutions.AndroidMySQLConnector.SocketSender.doInBackground(SocketSender.java:11)
2019-04-01 07:22:32.124 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:333)
2019-04-01 07:22:32.124 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-04-01 07:22:32.124 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
2019-04-01 07:22:32.125 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-04-01 07:22:32.125 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-04-01 07:22:32.125 3380-3432/hu.utomentomano.mysqltestv3 W/System.err:     at java.lang.Thread.run(Thread.java:764)
2019-04-01 07:22:32.275 3380-3430/hu.utomentomano.mysqltestv3 I/OpenGLRenderer: Initialized EGL, version 1.4
2019-04-01 07:22:32.305 3380-3430/hu.utomentomano.mysqltestv3 D/OpenGLRenderer: Swap behavior 1
2019-04-01 07:22:32.312 3380-3430/hu.utomentomano.mysqltestv3 D/EGL_emulation: eglCreateContext: 0x9c1841e0: maj 3 min 0 rcv 3
2019-04-01 07:22:32.316 3380-3430/hu.utomentomano.mysqltestv3 D/EGL_emulation: eglMakeCurrent: 0x9c1841e0: ver 3 0 (tinfo 0x9c183340)
2019-04-01 07:22:32.320 3380-3430/hu.utomentomano.mysqltestv3 E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2019-04-01 07:22:32.320 3380-3430/hu.utomentomano.mysqltestv3 E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008cdf
2019-04-01 07:22:32.320 3380-3430/hu.utomentomano.mysqltestv3 E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2019-04-01 07:22:32.324 3380-3430/hu.utomentomano.mysqltestv3 E/eglCodecCommon: glUtilsParamSize: unknow param 0x00008824
2019-04-01 07:22:32.585 3380-3430/hu.utomentomano.mysqltestv3 D/EGL_emulation: eglMakeCurrent: 0x9c1841e0: ver 3 0 (tinfo 0x9c183340)
=================================================================

----------------------------------------------------------------------------------------------------------------
MainActivity.java
----------------------------------------------------------------------------------------------------------------
```
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        DatabaseHelper databaseHelper = new DatabaseHelper();
    }
}

```
=================================================================

**Comment by boardy** [comment]
Hi Seng, 

Looks like you're getting something different now though.

I think I can see what the problem is from your database helper. 

You create the connection object but directly underneath that you create a statement and attempt to execute a query. The connection is an asychronous task so your connection and your statement are likely attempting to be done at same time but you're statement is likely getting called before the connection is fully established. 

I will do an update to the library to make this a bit more robust, but if you change your code to something like the following:

```
mysqlConnection = new Connection(/*Here I used the connection information what I sent to you.*/, new IConnectionInterface()
        {
            @Override
            public void actionCompleted()
            {
                Log.d(TAG, "actionCompleted: connected xxxxx");
                //Note that I executing the statement inside the actionCompleted call back.
                executeStatement();
            }
```

```
function executeStatement()
{
Statement statement = mysqlConnection.createStatement();
        Log.d(TAG, "DatabaseHelper: Connection started");
        statement.executeQuery("SELECT * FROM pricer", new IResultInterface() {
            @Override
            public void executionComplete(ResultSet resultSet) {
                Log.d(TAG, "executionComplete: before getNumRows");
                Log.d(TAG, "executionComplete: " + resultSet.getNumRows());
            }

            @Override
            public void handleInvalidSQLPacketException(InvalidSQLPacketException ex) {

            }

            @Override
            public void handleMySQLException(MySQLException ex) {

            }

            @Override
            public void handleIOException(IOException ex) {

            }

            @Override
            public void handleMySQLConnException(MySQLConnException ex) {

            }

            @Override
            public void handleException(Exception ex) {

            }
        });
}
```

Notice how I am calling the statement method from inside the `actionCompleted` callback. 

Hope this helps.

Thanks

Chris

**Comment by Asuki** [comment]
Hi Chris!

It worked 👍 
But I also got an Access denied error.

Thanks
Seng

**Comment by Asuki** [comment]
Hi Chris!

I got permissions for the test users. The connaction works correctly and I get data.

Thanks your help,
Seng

**Comment by boardy** [comment]
That's great. Glad you got it sorted. If you need anything else then let me know .

Thanks

Chris
